## Environment
Load packages and set parameters.

In [1]:
import matplotlib.pylab as plt
plt.style.use("ggplot")
%matplotlib inline

import numpy as np

import pandas as pd
pd.options.display.max_columns = None
pd.options.display.max_rows = None

import seaborn as sns

## Load data

In [2]:
tournament_id = 89132

In [3]:
df = pd.read_pickle(f"../data/interim/{tournament_id}-interim.pkl")

In [4]:
df.head()

,ResultID,FirstName,LastName,PDGANum,Division,Place,ToPar,Tied,Prize,DNF,Total,Avatar,ProfileURL,DivisionName,FormattedPlace,Class,Rating,RatingEffectiveDate,Location,Country,Nationality,AvatarURL,AverageRoundRating,RatingDiff,ToParString,ScoreID,Round,RoundDate,TeeTime,TeeStart,RoundScore,ScoreToPar,RoundToPar,Birdies,BirdieHoles,Bogeys,BogeyHoles,RoundComplete,RoundRating,CourseName,LayoutName,Holes,Par,Length,LengthUnits,Hole 1,Hole 2,Hole 3,Hole 4,Hole 5,Hole 6,Hole 7,Hole 8,Hole 9,Hole 10,Hole 11,Hole 12,Hole 13,Hole 14,Hole 15,Hole 16,Hole 17,Hole 18
0,211586222,Harry,Chace,131546,MPO,1,-11,False,$660,False,120,None,https://www.pdga.com/player/131546,Mixed Pro Open,1st,Professional,1023.0,2025-08-12,"East Greenwich, RI",US,US,None,1031,8,-11,25450418,1,2025-08-10,14:36:00,1,61,-7,-7,8,8,1,1,True,1032.0,Nockamixon State Park,LVO 2025,18,68,9325,Feet,4,4,3,4,2,3,3,4,4,3,3,2,5,5,2,3,3,4
1,211586222,Harry,Chace,131546,MPO,1,-11,False,$660,False,120,None,https://www.pdga.com/player/131546,Mixed Pro Open,1st,Professional,1023.0,2025-08-12,"East Greenwich, RI",US,US,None,1031,8,-11,25483066,2,2025-08-10,14:36:00,1,59,-4,-4,7,7,3,3,True,1030.0,The Preserve Disc Golf Course,LVO 2025,18,63,9073,Feet,3,3,3,2,3,4,4,4,4,4,3,2,3,4,3,3,2,5
2,211586679,Dylan,Horst,32599,MPO,5,-7,True,$230,False,124,None,https://www.pdga.com/player/32599,Mixed Pro Open,T-5th,Professional,1008.0,2025-08-12,"West Chester, PA",US,None,None,1017,9,-7,25449101,1,2025-08-10,14:00:00,1,62,-6,-6,7,7,1,1,True,1025.0,Nockamixon State Park,LVO 2025,18,68,9325,Feet,4,4,2,3,3,3,3,4,4,4,3,2,5,4,3,3,4,4
3,211586679,Dylan,Horst,32599,MPO,5,-7,True,$230,False,124,None,https://www.pdga.com/player/32599,Mixed Pro Open,T-5th,Professional,1008.0,2025-08-12,"West Chester, PA",US,None,None,1017,9,-7,25483067,2,2025-08-10,14:36:00,1,62,-1,-1,4,4,3,3,True,1008.0,The Preserve Disc Golf Course,LVO 2025,18,63,9073,Feet,3,4,2,2,3,4,4,4,3,4,3,3,5,4,4,3,3,4
4,211653303,Mike,Carman,48559,MPO,2,-9,True,$420,False,122,/files/styles/large/public/pictures/picture-18...,https://www.pdga.com/player/48559,Mixed Pro Open,T-2nd,Professional,992.0,2025-08-12,"Ottsville, PA",US,None,/files/styles/large/public/pictures/picture-18...,1024,32,-9,25449681,1,2025-08-10,14:24:00,1,62,-6,-6,7,7,1,1,True,1025.0,Nockamixon State Park,LVO 2025,18,68,9325,Feet,5,4,2,4,3,3,4,3,4,4,3,2,4,4,2,3,4,4

## Data understanding

In [5]:
df.shape # dimensions of the dataframe

(358, 63)

In [6]:
df.columns

Index(['ResultID', 'FirstName', 'LastName', 'PDGANum', 'Division', 'Place',
       'ToPar', 'Tied', 'Prize', 'DNF', 'Total', 'Avatar', 'ProfileURL',
       'DivisionName', 'FormattedPlace', 'Class', 'Rating',
       'RatingEffectiveDate', 'Location', 'Country', 'Nationality',
       'AvatarURL', 'AverageRoundRating', 'RatingDiff', 'ToParString',
       'ScoreID', 'Round', 'RoundDate', 'TeeTime', 'TeeStart', 'RoundScore',
       'ScoreToPar', 'RoundToPar', 'Birdies', 'BirdieHoles', 'Bogeys',
       'BogeyHoles', 'RoundComplete', 'RoundRating', 'CourseName',
       'LayoutName', 'Holes', 'Par', 'Length', 'LengthUnits', 'Hole 1',
       'Hole 2', 'Hole 3', 'Hole 4', 'Hole 5', 'Hole 6', 'Hole 7', 'Hole 8',
       'Hole 9', 'Hole 10', 'Hole 11', 'Hole 12', 'Hole 13', 'Hole 14',
       'Hole 15', 'Hole 16', 'Hole 17', 'Hole 18'],
      dtype='object')

In [7]:
df.RoundComplete.value_counts()

RoundComplete
True    358
Name: count, dtype: int64

In [8]:
df.dtypes

ResultID                 int64
FirstName               object
LastName                object
PDGANum                  int64
Division                object
Place                    int64
ToPar                    int64
Tied                      bool
Prize                   object
DNF                       bool
Total                    int64
Avatar                  object
ProfileURL              object
DivisionName            object
FormattedPlace          object
Class                   object
Rating                 float64
RatingEffectiveDate     object
Location                object
Country                 object
Nationality             object
AvatarURL               object
AverageRoundRating       int64
RatingDiff               int64
ToParString             object
ScoreID                  int64
Round                    int64
RoundDate               object
TeeTime                 object
TeeStart                object
RoundScore               int64
ScoreToPar              object
RoundToPar               int64
Birdies                  int64
BirdieHoles              int64
Bogeys                   int64
BogeyHoles               int64
RoundComplete             bool
RoundRating            float64
CourseName              object
LayoutName              object
Holes                    int64
Par                      int64
Length                   int64
LengthUnits             object
Hole 1                   int64
Hole 2                   int64
Hole 3                   int64
Hole 4                   int64
Hole 5                   int64
Hole 6                   int64
Hole 7                   int64
Hole 8                   int64
Hole 9                   int64
Hole 10                  int64
Hole 11                  int64
Hole 12                  int64
Hole 13                  int64
Hole 14                  int64
Hole 15                  int64
Hole 16                  int64
Hole 17                  int64
Hole 18                  int64
dtype: object

In [9]:
df.describe()

,ResultID,PDGANum,Place,ToPar,Total,Rating,AverageRoundRating,RatingDiff,ScoreID,Round,RoundScore,RoundToPar,Birdies,BirdieHoles,Bogeys,BogeyHoles,RoundRating,Holes,Par,Length,Hole 1,Hole 2,Hole 3,Hole 4,Hole 5,Hole 6,Hole 7,Hole 8,Hole 9,Hole 10,Hole 11,Hole 12,Hole 13,Hole 14,Hole 15,Hole 16,Hole 17,Hole 18
count,3.580000e+02,358.000000,358.000000,358.000000,358.000000,356.000000,358.000000,358.000000,3.580000e+02,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,354.000000,358.0,358.000000,358.000000,358.00000,358.000000,358.000000,358.000000,358.000000,358.000000,358.00000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000,358.000000
mean,2.118039e+08,172555.625698,21.480447,36.815642,171.284916,927.794944,931.888268,4.466480,2.545574e+07,1.497207,84.106145,18.435754,2.178771,2.094972,10.452514,7.245810,931.627119,18.0,65.670391,9165.094972,4.76257,3.717877,2.972067,3.743017,3.960894,4.094972,3.47486,4.759777,4.240223,4.617318,3.687151,3.483240,5.027933,5.173184,4.005587,3.762570,3.731844,4.729050
std,1.666446e+05,81969.349076,18.287722,137.521537,141.102432,46.785758,48.777134,22.008726,2.054551e+04,0.500692,97.647998,97.660132,2.318214,1.930712,6.883320,3.318047,51.490057,0.0,2.466076,232.869680,1.67434,0.860762,0.656194,1.058985,0.966458,0.905586,0.82888,1.017137,1.046992,1.174630,0.954073,0.862216,1.280888,1.317053,1.252436,1.203192,0.917091,1.027245
min,2.115814e+08,10628.000000,1.000000,-11.000000,120.000000,755.000000,742.000000,-60.000000,2.542156e+07,1.000000,57.000000,-7.000000,0.000000,0.000000,0.000000,0.000000,720.000000,18.0,63.000000,8188.000000,2.00000,2.000000,2.000000,2.000000,2.000000,3.000000,2.00000,3.000000,2.000000,3.000000,2.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.116170e+08,110670.000000,7.000000,7.000000,138.000000,903.000000,904.000000,-9.000000,2.543652e+07,1.000000,69.000000,3.000000,0.000000,0.000000,6.000000,5.000000,901.000000,18.0,63.000000,9073.000000,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000,3.00000,4.000000,3.000000,4.000000,3.000000,3.000000,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000
50%,2.118063e+08,170744.000000,16.000000,16.000000,147.000000,933.500000,934.000000,5.000000,2.545042e+07,1.000000,73.000000,7.000000,2.000000,2.000000,9.000000,7.000000,936.000000,18.0,68.000000,9325.000000,5.00000,4.000000,3.000000,4.000000,4.000000,4.000000,3.00000,5.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,4.000000,3.000000,4.000000,5.000000
75%,2.119723e+08,243233.750000,30.000000,24.000000,156.000000,962.250000,969.000000,20.000000,2.547565e+07,2.000000,78.000000,12.000000,3.000000,3.000000,13.000000,9.000000,966.000000,18.0,68.000000,9325.000000,6.00000,4.000000,3.000000,4.000000,4.000000,5.000000,4.00000,5.000000,5.000000,5.000000,4.000000,4.000000,6.000000,6.000000,5.000000,4.000000,4.000000,5.000000
max,2.120254e+08,312951.000000,70.000000,947.000000,999.000000,1026.000000,1031.000000,73.000000,2.548307e+07,2.000000,999.000000,936.000000,20.000000,9.000000,72.000000,18.000000,1044.000000,18.0,68.000000,9325.000000,10.00000,7.000000,7.000000,8.000000,8.000000,8.000000,7.00000,8.000000,9.000000,11.000000,8.000000,7.000000,10.000000,11.000000,9.000000,10.000000,8.000000,8.000000

### Remove unwanted columns

In [10]:
df = df[['ResultID', 'FirstName', 'LastName', 'PDGANum', 'Division', 'Place',
       'ToPar', 'Tied', 'Prize', 'DNF', 'Total', 
         #'Avatar', 'ProfileURL', 'DivisionName', 
         'FormattedPlace', 'Class', 'Rating',
       'RatingEffectiveDate', 'Location', 'Country', 'Nationality',
       #'AvatarURL', 
         'AverageRoundRating', 'RatingDiff', 
         #'ToParString',
       'ScoreID', 'Round', 
         #'RoundDate', #all rounds show same date
         'TeeTime', 
         #'TeeStart',  # all started on Hole 1 e.g. tee times 
         'RoundScore',
       'ScoreToPar', 
         #'RoundToPar', 
         'Birdies', 
        #'BirdieHoles', 
         'Bogeys',
       #'BogeyHoles', 
        #'RoundComplete', 
         'RoundRating', 'CourseName',
       'LayoutName', 'Holes', 'Par', 'Length', 
         #'LengthUnits', 
         'Hole 1',
       'Hole 2', 'Hole 3', 'Hole 4', 'Hole 5', 'Hole 6', 'Hole 7', 'Hole 8',
       'Hole 9', 'Hole 10', 'Hole 11', 'Hole 12', 'Hole 13', 'Hole 14',
       'Hole 15', 'Hole 16', 'Hole 17', 'Hole 18']].copy()

#df.head()

In [11]:
### Rename columns
rename_dict = {"ResultID": "result_id", "FirstName": "first_name","LastName": "last_name",
               "PDGANum": "pdga_num","Division": "tournament_division","Place": "tournament_place","ToPar": "tournament_total_to_par",
               "Tied": "tied_finish", "Prize": "prize", "DNF": "tournament_dnf", "Total": "shot_total", 
               "FormattedPlace": "formatted_place", "Class": "player_class",
               "Rating": "player_rating", "RatingEffectiveDate": "rating_effective_date", "Location": "location",
               "Country": "country", "Nationality": "nationality", "AverageRoundRating": "tournament_average_rating",
               "RatingDiff": "tournament_rating_delta", "ScoreID": "score_id", "Round": "round", "TeeTime": "tee_time",
               "RoundScore": "round_score",
               "ScoreToPar": "score_to_par", "Birdies": "num_birdies", "Bogeys": "num_bogeys", "RoundRating": "round_rating",
               "CourseName": "course_name", "LayoutName": "layout_name",
               "Holes": "num_holes", "Par": "par", "Length": "layout_length"
              }

df = df.rename(columns=rename_dict).reset_index(drop=True).copy()
#df.head()

### Feature creation

In [12]:
# Split "location" into town and state
df[["city", "state"]] = df.location.str.split(',', expand=True)

df = df.drop(["location"], axis=1).copy()
#df.head()

In [13]:
# Recast prize into prize_usd so that it may be an integer
df["prize"] = df.prize.replace({"": "$0", })
df["prize_usd"] = df.prize.str.extract(r'(\d+)')
df["prize_usd"] = df["prize_usd"].astype("int64")

#df.prize_usd.value_counts()

df = df.drop(["prize"], axis=1).copy()
#df.head()

In [14]:
# Recast "player_rating" to be an Int64 dtype which allows missing values
df['player_rating'] = df['player_rating'].astype("Int64")
df['round_rating'] = df['round_rating'].astype("Int64")

#df.head()

In [15]:
# Create "round_dnf" column
df['round_dnf'] = df['round_score'] == 999

In [16]:
# Recast "score_to_par" as an integer
df["score_to_par"] = df.score_to_par.replace({"E": 0})
df["score_to_par"] = df.score_to_par.astype(int)

## Reorder columns for better readability

In [17]:
df.columns

Index(['result_id', 'first_name', 'last_name', 'pdga_num',
       'tournament_division', 'tournament_place', 'tournament_total_to_par',
       'tied_finish', 'tournament_dnf', 'shot_total', 'formatted_place',
       'player_class', 'player_rating', 'rating_effective_date', 'country',
       'nationality', 'tournament_average_rating', 'tournament_rating_delta',
       'score_id', 'round', 'tee_time', 'round_score', 'score_to_par',
       'num_birdies', 'num_bogeys', 'round_rating', 'course_name',
       'layout_name', 'num_holes', 'par', 'layout_length', 'Hole 1', 'Hole 2',
       'Hole 3', 'Hole 4', 'Hole 5', 'Hole 6', 'Hole 7', 'Hole 8', 'Hole 9',
       'Hole 10', 'Hole 11', 'Hole 12', 'Hole 13', 'Hole 14', 'Hole 15',
       'Hole 16', 'Hole 17', 'Hole 18', 'city', 'state', 'prize_usd',
       'round_dnf'],
      dtype='object')

In [18]:
new_col_order = ['first_name', 'last_name', 
                 'city', 'state', 'country', 'nationality',
                 'pdga_num', 'player_rating', 'rating_effective_date', 'player_class',
                 'result_id', 'tournament_division', 'tournament_place', 'tied_finish', 'formatted_place',
                   'shot_total','tournament_total_to_par','prize_usd',
               'tournament_dnf',  
               'tournament_average_rating', 'tournament_rating_delta', 
                 'score_id','round', 'tee_time', 'course_name', 'layout_name', 
                 'par','round_score',  'score_to_par', 'round_dnf',
                 'num_birdies','num_bogeys', 'round_rating', 
                   'num_holes', 'layout_length', 
                 'Hole 1', 'Hole 2', 'Hole 3', 'Hole 4', 'Hole 5',
       'Hole 6', 'Hole 7', 'Hole 8', 'Hole 9', 'Hole 10', 'Hole 11', 'Hole 12',
       'Hole 13', 'Hole 14', 'Hole 15', 'Hole 16', 'Hole 17', 'Hole 18']

df = df[new_col_order].copy()
df.head()

,first_name,last_name,city,state,country,nationality,pdga_num,player_rating,rating_effective_date,player_class,result_id,tournament_division,tournament_place,tied_finish,formatted_place,shot_total,tournament_total_to_par,prize_usd,tournament_dnf,tournament_average_rating,tournament_rating_delta,score_id,round,tee_time,course_name,layout_name,par,round_score,score_to_par,round_dnf,num_birdies,num_bogeys,round_rating,num_holes,layout_length,Hole 1,Hole 2,Hole 3,Hole 4,Hole 5,Hole 6,Hole 7,Hole 8,Hole 9,Hole 10,Hole 11,Hole 12,Hole 13,Hole 14,Hole 15,Hole 16,Hole 17,Hole 18
0,Harry,Chace,East Greenwich,RI,US,US,131546,1023,2025-08-12,Professional,211586222,MPO,1,False,1st,120,-11,660,False,1031,8,25450418,1,14:36:00,Nockamixon State Park,LVO 2025,68,61,-7,False,8,1,1032,18,9325,4,4,3,4,2,3,3,4,4,3,3,2,5,5,2,3,3,4
1,Harry,Chace,East Greenwich,RI,US,US,131546,1023,2025-08-12,Professional,211586222,MPO,1,False,1st,120,-11,660,False,1031,8,25483066,2,14:36:00,The Preserve Disc Golf Course,LVO 2025,63,59,-4,False,7,3,1030,18,9073,3,3,3,2,3,4,4,4,4,4,3,2,3,4,3,3,2,5
2,Dylan,Horst,West Chester,PA,US,None,32599,1008,2025-08-12,Professional,211586679,MPO,5,True,T-5th,124,-7,230,False,1017,9,25449101,1,14:00:00,Nockamixon State Park,LVO 2025,68,62,-6,False,7,1,1025,18,9325,4,4,2,3,3,3,3,4,4,4,3,2,5,4,3,3,4,4
3,Dylan,Horst,West Chester,PA,US,None,32599,1008,2025-08-12,Professional,211586679,MPO,5,True,T-5th,124,-7,230,False,1017,9,25483067,2,14:36:00,The Preserve Disc Golf Course,LVO 2025,63,62,-1,False,4,3,1008,18,9073,3,4,2,2,3,4,4,4,3,4,3,3,5,4,4,3,3,4
4,Mike,Carman,Ottsville,PA,US,None,48559,992,2025-08-12,Professional,211653303,MPO,2,True,T-2nd,122,-9,420,False,1024,32,25449681,1,14:24:00,Nockamixon State Park,LVO 2025,68,62,-6,False,7,1,1025,18,9325,5,4,2,4,3,3,4,3,4,4,3,2,4,4,2,3,4,4

## Set column datatypes appropriately

In [28]:
df['rating_effective_date'] = pd.to_datetime(df['rating_effective_date'])

## Save dataframe to `/data/processed/`

In [31]:
#pd.to_pickle(df, f"../data/processed/{tournament_id}-processed.pkl")